### ISSUE TITLE
The tutorial code 1-plot-aims-ereefs-data.Rmd appears to be out of date

### ISSUE THREAD

**Issue by gerard-ricardo** [aims-ks/ereefs-r-scripts#1]
Trouble reading in OPeNDAP URL as well as some other  issues (lat data produced as a matrix etc).

**Comment by mhn17** [comment]
The OPeNDAP URLs were not accessible because the THREDDS server was offline due to system maintenance. The server is back up and running and you shouldn't have troubles with the URLs anymore. I will have a look at the code to make sure it's up to date.

**Comment by mhn17** [comment]
Code is working, other issues might have been related to the THREDDS server being offline.
